name: Backend CI

on:
  push:
    paths:
      - 'AdminStaffSystem/**'
  pull_request:
    paths:
      - 'AdminStaffSystem/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        cd AdminStaffSystem
        mvn clean install
