name: Backend CD

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Deploy to GlassFish
        env:
          GLASSFISH_ADMIN_USER: admin
          GLASSFISH_ADMIN_PASSWORD: ${{ secrets.GLASSFISH_ADMIN_PASSWORD }}
          GLASSFISH_HOME: /home/musharraf/GlassFish_Server
          WAR_NAME: AdminStaffSystem
        run: |
          echo "AS_ADMIN_PASSWORD=${GLASSFISH_ADMIN_PASSWORD}" > password.txt
          $GLASSFISH_HOME/bin/asadmin start-domain
          # Undeploy old WAR if exists
          $GLASSFISH_HOME/bin/asadmin --user $GLASSFISH_ADMIN_USER --passwordfile password.txt undeploy $WAR_NAME.war || true
          # Deploy new WAR
          $GLASSFISH_HOME/bin/asadmin --user $GLASSFISH_ADMIN_USER --passwordfile password.txt deploy target/$WAR_NAME.war
          $GLASSFISH_HOME/bin/asadmin stop-domain
